<!DOCTYPE html>
<html>
<head>
  <title>Chaining a catch method</title>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="../assert.css">
  <script src="../assert.js"></script>
</head>
<body>

  <!-- listing 6.13 Chaining a catch method -->
  <script>
    const promise = new Promise((resolve, reject) => {
      reject("Explicitly reject a promise");
    });

    promise.then(
      () => fail("Happy path, wont be called!"))
        .catch(() => pass("Promise was also rejected")
    );    
  </script>
</body>
</html>
